Update ss-rules

diff --git a/files/root/usr/bin/ss-rules b/files/root/usr/bin/ss-rules
--- a/files/root/usr/bin/ss-rules
+++ b/files/root/usr/bin/ss-rules
@@ -294,6 +294,8 @@ elif [ "$TPROXY" = 2 ]; then
 fi
 
 flush_rules && ipset_init && dnsmasq_ipset && ipt_nat && ipt_mangle && export_ipt_rules
-RET=$?
-[ "$RET" = 0 ] || loger 3 "Start failed!"
-exit $RET
+
+#RET=$?
+#[ "$RET" = 0 ] || loger 3 "Start failed!"
+#exit $RET
+exit
